services:
  api:
    build: .
    container_name: phone_api
    depends_on:
      - redis
    volumes:
      - .:/api
    ports:
      - 8000:8000
    networks:
      - ave_network
  
  redis:
    container_name: redis
    image: redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - ave_network

networks:
  ave_network:
    driver: bridge